#group:
#  group_name: <group_name>
#  component_name: <component_name>
#  buttons: [[button_name1,function_name1,parameter_name2,
#    [button_name2,function_name2,parameter_name2]]

group1:
  group_name: base
  component_name: base
  buttons: [[stop,trigger,stop],
    [init,trigger,init],
    [recover,trigger,recover]]
group3:
  group_name: tray
  component_name: tray
  buttons: [[stop,trigger,stop],
    [init,trigger,init],
    [recover,trigger,recover],
    [home,move,home],
    [displayup,move,displayup],
    [displaydown,move,displaydown],
  ]
